"""add to_phone to outreach

Revision ID: 10c3cb720177
Revises: 5c038ba816d6
Create Date: 2026-09-05 12:25:22.562269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10c3cb720177'
down_revision: Union[str, Sequence[str], None] = '5c038ba816d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outreach', sa.Column('to_phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outreach', 'to_phone')
    # ### end Alembic commands ###
