"""Add outreach tables

Revision ID: 5c038ba816d6
Revises: 9e28827ae948
Create Date: 2026-09-05 01:06:06.348467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c038ba816d6'
down_revision: Union[str, Sequence[str], None] = '9e28827ae948'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('smtp_credentials',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('smtp_host', sa.String(), nullable=False),
    sa.Column('smtp_port', sa.Integer(), nullable=True),
    sa.Column('encrypted_password', sa.String(), nullable=False),
    sa.Column('daily_limit', sa.Integer(), nullable=True),
    sa.Column('sender_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_smtp_credentials_user_id'), 'smtp_credentials', ['user_id'], unique=False)
    op.create_table('suppressions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'email', name='uq_suppression_user_email')
    )
    op.create_index(op.f('ix_suppressions_email'), 'suppressions', ['email'], unique=False)
    op.create_index(op.f('ix_suppressions_user_id'), 'suppressions', ['user_id'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('smtp_credential_id', sa.String(), nullable=True),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.Column('email_subject_template', sa.String(), nullable=True),
    sa.Column('sender_name', sa.String(), nullable=True),
    sa.Column('physical_address', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('batch_size', sa.Integer(), nullable=True),
    sa.Column('delay_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ),
    sa.ForeignKeyConstraint(['smtp_credential_id'], ['smtp_credentials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_user_id'), 'campaigns', ['user_id'], unique=False)
    op.create_table('send_log',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('credential_id', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['credential_id'], ['smtp_credentials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('credential_id', 'date', name='uq_sendlog_cred_date')
    )
    op.create_table('outreach',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('to_email', sa.String(), nullable=True),
    sa.Column('generated_subject', sa.String(), nullable=True),
    sa.Column('generated_message', sa.String(), nullable=True),
    sa.Column('user_edited', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('skip_reason', sa.String(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outreach_campaign_id'), 'outreach', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_outreach_status'), 'outreach', ['status'], unique=False)
    op.create_table('user_docs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('content_text', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_docs_campaign_id'), 'user_docs', ['campaign_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_docs_campaign_id'), table_name='user_docs')
    op.drop_table('user_docs')
    op.drop_index(op.f('ix_outreach_status'), table_name='outreach')
    op.drop_index(op.f('ix_outreach_campaign_id'), table_name='outreach')
    op.drop_table('outreach')
    op.drop_table('send_log')
    op.drop_index(op.f('ix_campaigns_user_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_suppressions_user_id'), table_name='suppressions')
    op.drop_index(op.f('ix_suppressions_email'), table_name='suppressions')
    op.drop_table('suppressions')
    op.drop_index(op.f('ix_smtp_credentials_user_id'), table_name='smtp_credentials')
    op.drop_table('smtp_credentials')
    # ### end Alembic commands ###
