"""Add channel to CampaignRecord

Revision ID: 627adf08a33d
Revises: 10c3cb720177
Create Date: 2026-09-16 04:04:50.595711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '627adf08a33d'
down_revision: Union[str, Sequence[str], None] = '10c3cb720177'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('channel', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'channel')
    # ### end Alembic commands ###
